/** Auto-generated from ../src/data/teams.ts and ../src/data/players.ts */
export const WORLD_CUP_2026_GROUPS = [
  {
    "code": "A",
    "label": "Group A",
    "order": 1
  },
  {
    "code": "B",
    "label": "Group B",
    "order": 2
  },
  {
    "code": "C",
    "label": "Group C",
    "order": 3
  },
  {
    "code": "D",
    "label": "Group D",
    "order": 4
  },
  {
    "code": "E",
    "label": "Group E",
    "order": 5
  },
  {
    "code": "F",
    "label": "Group F",
    "order": 6
  },
  {
    "code": "G",
    "label": "Group G",
    "order": 7
  },
  {
    "code": "H",
    "label": "Group H",
    "order": 8
  },
  {
    "code": "I",
    "label": "Group I",
    "order": 9
  },
  {
    "code": "J",
    "label": "Group J",
    "order": 10
  },
  {
    "code": "K",
    "label": "Group K",
    "order": 11
  },
  {
    "code": "L",
    "label": "Group L",
    "order": 12
  }
] as const;

export const WORLD_CUP_2026_TEAMS = [
  {
    "frontendId": "usa",
    "name": "United States",
    "shortName": "USA",
    "code": "USA",
    "groupCode": "A",
    "flagUrl": "https://flagcdn.com/w80/us.png",
    "isEliminated": false
  },
  {
    "frontendId": "mex",
    "name": "Mexico",
    "shortName": "MEX",
    "code": "MEX",
    "groupCode": "A",
    "flagUrl": "https://flagcdn.com/w80/mx.png",
    "isEliminated": false
  },
  {
    "frontendId": "col",
    "name": "Colombia",
    "shortName": "COL",
    "code": "COL",
    "groupCode": "A",
    "flagUrl": "https://flagcdn.com/w80/co.png",
    "isEliminated": false
  },
  {
    "frontendId": "mar",
    "name": "Morocco",
    "shortName": "MAR",
    "code": "MAR",
    "groupCode": "A",
    "flagUrl": "https://flagcdn.com/w80/ma.png",
    "isEliminated": false
  },
  {
    "frontendId": "bra",
    "name": "Brazil",
    "shortName": "BRA",
    "code": "BRA",
    "groupCode": "B",
    "flagUrl": "https://flagcdn.com/w80/br.png",
    "isEliminated": false
  },
  {
    "frontendId": "jpn",
    "name": "Japan",
    "shortName": "JPN",
    "code": "JPN",
    "groupCode": "B",
    "flagUrl": "https://flagcdn.com/w80/jp.png",
    "isEliminated": false
  },
  {
    "frontendId": "nga",
    "name": "Nigeria",
    "shortName": "NGA",
    "code": "NGA",
    "groupCode": "B",
    "flagUrl": "https://flagcdn.com/w80/ng.png",
    "isEliminated": false
  },
  {
    "frontendId": "tur",
    "name": "Turkey",
    "shortName": "TUR",
    "code": "TUR",
    "groupCode": "B",
    "flagUrl": "https://flagcdn.com/w80/tr.png",
    "isEliminated": false
  },
  {
    "frontendId": "arg",
    "name": "Argentina",
    "shortName": "ARG",
    "code": "ARG",
    "groupCode": "C",
    "flagUrl": "https://flagcdn.com/w80/ar.png",
    "isEliminated": false
  },
  {
    "frontendId": "per",
    "name": "Peru",
    "shortName": "PER",
    "code": "PER",
    "groupCode": "C",
    "flagUrl": "https://flagcdn.com/w80/pe.png",
    "isEliminated": false
  },
  {
    "frontendId": "ukr",
    "name": "Ukraine",
    "shortName": "UKR",
    "code": "UKR",
    "groupCode": "C",
    "flagUrl": "https://flagcdn.com/w80/ua.png",
    "isEliminated": false
  },
  {
    "frontendId": "aus",
    "name": "Australia",
    "shortName": "AUS",
    "code": "AUS",
    "groupCode": "C",
    "flagUrl": "https://flagcdn.com/w80/au.png",
    "isEliminated": false
  },
  {
    "frontendId": "fra",
    "name": "France",
    "shortName": "FRA",
    "code": "FRA",
    "groupCode": "D",
    "flagUrl": "https://flagcdn.com/w80/fr.png",
    "isEliminated": false
  },
  {
    "frontendId": "sen",
    "name": "Senegal",
    "shortName": "SEN",
    "code": "SEN",
    "groupCode": "D",
    "flagUrl": "https://flagcdn.com/w80/sn.png",
    "isEliminated": false
  },
  {
    "frontendId": "kor",
    "name": "South Korea",
    "shortName": "KOR",
    "code": "KOR",
    "groupCode": "D",
    "flagUrl": "https://flagcdn.com/w80/kr.png",
    "isEliminated": false
  },
  {
    "frontendId": "crc",
    "name": "Costa Rica",
    "shortName": "CRC",
    "code": "CRC",
    "groupCode": "D",
    "flagUrl": "https://flagcdn.com/w80/cr.png",
    "isEliminated": false
  },
  {
    "frontendId": "eng",
    "name": "England",
    "shortName": "ENG",
    "code": "ENG",
    "groupCode": "E",
    "flagUrl": "https://flagcdn.com/w80/gb-eng.png",
    "isEliminated": false
  },
  {
    "frontendId": "ita",
    "name": "Italy",
    "shortName": "ITA",
    "code": "ITA",
    "groupCode": "E",
    "flagUrl": "https://flagcdn.com/w80/it.png",
    "isEliminated": false
  },
  {
    "frontendId": "ecu",
    "name": "Ecuador",
    "shortName": "ECU",
    "code": "ECU",
    "groupCode": "E",
    "flagUrl": "https://flagcdn.com/w80/ec.png",
    "isEliminated": false
  },
  {
    "frontendId": "chn",
    "name": "China",
    "shortName": "CHN",
    "code": "CHN",
    "groupCode": "E",
    "flagUrl": "https://flagcdn.com/w80/cn.png",
    "isEliminated": false
  },
  {
    "frontendId": "ger",
    "name": "Germany",
    "shortName": "GER",
    "code": "GER",
    "groupCode": "F",
    "flagUrl": "https://flagcdn.com/w80/de.png",
    "isEliminated": false
  },
  {
    "frontendId": "chl",
    "name": "Chile",
    "shortName": "CHL",
    "code": "CHL",
    "groupCode": "F",
    "flagUrl": "https://flagcdn.com/w80/cl.png",
    "isEliminated": false
  },
  {
    "frontendId": "cmr",
    "name": "Cameroon",
    "shortName": "CMR",
    "code": "CMR",
    "groupCode": "F",
    "flagUrl": "https://flagcdn.com/w80/cm.png",
    "isEliminated": false
  },
  {
    "frontendId": "nzl",
    "name": "New Zealand",
    "shortName": "NZL",
    "code": "NZL",
    "groupCode": "F",
    "flagUrl": "https://flagcdn.com/w80/nz.png",
    "isEliminated": false
  },
  {
    "frontendId": "esp",
    "name": "Spain",
    "shortName": "ESP",
    "code": "ESP",
    "groupCode": "G",
    "flagUrl": "https://flagcdn.com/w80/es.png",
    "isEliminated": false
  },
  {
    "frontendId": "cro",
    "name": "Croatia",
    "shortName": "CRO",
    "code": "CRO",
    "groupCode": "G",
    "flagUrl": "https://flagcdn.com/w80/hr.png",
    "isEliminated": false
  },
  {
    "frontendId": "can",
    "name": "Canada",
    "shortName": "CAN",
    "code": "CAN",
    "groupCode": "G",
    "flagUrl": "https://flagcdn.com/w80/ca.png",
    "isEliminated": false
  },
  {
    "frontendId": "sau",
    "name": "Saudi Arabia",
    "shortName": "KSA",
    "code": "KSA",
    "groupCode": "G",
    "flagUrl": "https://flagcdn.com/w80/sa.png",
    "isEliminated": false
  },
  {
    "frontendId": "por",
    "name": "Portugal",
    "shortName": "POR",
    "code": "POR",
    "groupCode": "H",
    "flagUrl": "https://flagcdn.com/w80/pt.png",
    "isEliminated": false
  },
  {
    "frontendId": "uru",
    "name": "Uruguay",
    "shortName": "URU",
    "code": "URU",
    "groupCode": "H",
    "flagUrl": "https://flagcdn.com/w80/uy.png",
    "isEliminated": false
  },
  {
    "frontendId": "gha",
    "name": "Ghana",
    "shortName": "GHA",
    "code": "GHA",
    "groupCode": "H",
    "flagUrl": "https://flagcdn.com/w80/gh.png",
    "isEliminated": false
  },
  {
    "frontendId": "irn",
    "name": "Iran",
    "shortName": "IRN",
    "code": "IRN",
    "groupCode": "H",
    "flagUrl": "https://flagcdn.com/w80/ir.png",
    "isEliminated": false
  },
  {
    "frontendId": "ned",
    "name": "Netherlands",
    "shortName": "NED",
    "code": "NED",
    "groupCode": "I",
    "flagUrl": "https://flagcdn.com/w80/nl.png",
    "isEliminated": false
  },
  {
    "frontendId": "sui",
    "name": "Switzerland",
    "shortName": "SUI",
    "code": "SUI",
    "groupCode": "I",
    "flagUrl": "https://flagcdn.com/w80/ch.png",
    "isEliminated": false
  },
  {
    "frontendId": "par",
    "name": "Paraguay",
    "shortName": "PAR",
    "code": "PAR",
    "groupCode": "I",
    "flagUrl": "https://flagcdn.com/w80/py.png",
    "isEliminated": false
  },
  {
    "frontendId": "idn",
    "name": "Indonesia",
    "shortName": "IDN",
    "code": "IDN",
    "groupCode": "I",
    "flagUrl": "https://flagcdn.com/w80/id.png",
    "isEliminated": false
  },
  {
    "frontendId": "bel",
    "name": "Belgium",
    "shortName": "BEL",
    "code": "BEL",
    "groupCode": "J",
    "flagUrl": "https://flagcdn.com/w80/be.png",
    "isEliminated": false
  },
  {
    "frontendId": "den",
    "name": "Denmark",
    "shortName": "DEN",
    "code": "DEN",
    "groupCode": "J",
    "flagUrl": "https://flagcdn.com/w80/dk.png",
    "isEliminated": false
  },
  {
    "frontendId": "alg",
    "name": "Algeria",
    "shortName": "ALG",
    "code": "ALG",
    "groupCode": "J",
    "flagUrl": "https://flagcdn.com/w80/dz.png",
    "isEliminated": false
  },
  {
    "frontendId": "bol",
    "name": "Bolivia",
    "shortName": "BOL",
    "code": "BOL",
    "groupCode": "J",
    "flagUrl": "https://flagcdn.com/w80/bo.png",
    "isEliminated": false
  },
  {
    "frontendId": "srb",
    "name": "Serbia",
    "shortName": "SRB",
    "code": "SRB",
    "groupCode": "K",
    "flagUrl": "https://flagcdn.com/w80/rs.png",
    "isEliminated": false
  },
  {
    "frontendId": "swe",
    "name": "Sweden",
    "shortName": "SWE",
    "code": "SWE",
    "groupCode": "K",
    "flagUrl": "https://flagcdn.com/w80/se.png",
    "isEliminated": false
  },
  {
    "frontendId": "egy",
    "name": "Egypt",
    "shortName": "EGY",
    "code": "EGY",
    "groupCode": "K",
    "flagUrl": "https://flagcdn.com/w80/eg.png",
    "isEliminated": false
  },
  {
    "frontendId": "jam",
    "name": "Jamaica",
    "shortName": "JAM",
    "code": "JAM",
    "groupCode": "K",
    "flagUrl": "https://flagcdn.com/w80/jm.png",
    "isEliminated": false
  },
  {
    "frontendId": "pol",
    "name": "Poland",
    "shortName": "POL",
    "code": "POL",
    "groupCode": "L",
    "flagUrl": "https://flagcdn.com/w80/pl.png",
    "isEliminated": false
  },
  {
    "frontendId": "wal",
    "name": "Wales",
    "shortName": "WAL",
    "code": "WAL",
    "groupCode": "L",
    "flagUrl": "https://flagcdn.com/w80/gb-wls.png",
    "isEliminated": false
  },
  {
    "frontendId": "tun",
    "name": "Tunisia",
    "shortName": "TUN",
    "code": "TUN",
    "groupCode": "L",
    "flagUrl": "https://flagcdn.com/w80/tn.png",
    "isEliminated": false
  },
  {
    "frontendId": "pan",
    "name": "Panama",
    "shortName": "PAN",
    "code": "PAN",
    "groupCode": "L",
    "flagUrl": "https://flagcdn.com/w80/pa.png",
    "isEliminated": false
  }
] as const;

export const WORLD_CUP_2026_PLAYERS = [
  {
    "frontendId": "p_usa_1",
    "name": "Matt Turner",
    "shortName": "Turner",
    "teamCode": "USA",
    "position": "GK",
    "price": "4.50",
    "totalPoints": 20,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_usa_2",
    "name": "Sergino Dest",
    "shortName": "Dest",
    "teamCode": "USA",
    "position": "DEF",
    "price": "5.00",
    "totalPoints": 18,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_usa_3",
    "name": "Christian Pulisic",
    "shortName": "Pulisic",
    "teamCode": "USA",
    "position": "MID",
    "price": "8.50",
    "totalPoints": 42,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_usa_4",
    "name": "Weston McKennie",
    "shortName": "McKennie",
    "teamCode": "USA",
    "position": "MID",
    "price": "6.50",
    "totalPoints": 28,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_usa_5",
    "name": "Ricardo Pepi",
    "shortName": "Pepi",
    "teamCode": "USA",
    "position": "FWD",
    "price": "7.00",
    "totalPoints": 32,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_bra_1",
    "name": "Alisson",
    "shortName": "Alisson",
    "teamCode": "BRA",
    "position": "GK",
    "price": "5.50",
    "totalPoints": 28,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_bra_2",
    "name": "Marquinhos",
    "shortName": "Marquinhos",
    "teamCode": "BRA",
    "position": "DEF",
    "price": "6.00",
    "totalPoints": 25,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_bra_3",
    "name": "VinÃ­cius Jr",
    "shortName": "VinÃ­cius Jr",
    "teamCode": "BRA",
    "position": "FWD",
    "price": "11.50",
    "totalPoints": 58,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_bra_4",
    "name": "Rodrygo",
    "shortName": "Rodrygo",
    "teamCode": "BRA",
    "position": "MID",
    "price": "9.00",
    "totalPoints": 40,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_bra_5",
    "name": "Endrick",
    "shortName": "Endrick",
    "teamCode": "BRA",
    "position": "FWD",
    "price": "8.00",
    "totalPoints": 35,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_arg_1",
    "name": "Emiliano MartÃ­nez",
    "shortName": "E. MartÃ­nez",
    "teamCode": "ARG",
    "position": "GK",
    "price": "5.50",
    "totalPoints": 30,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_arg_2",
    "name": "Cuti Romero",
    "shortName": "Romero",
    "teamCode": "ARG",
    "position": "DEF",
    "price": "6.00",
    "totalPoints": 27,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_arg_3",
    "name": "Lionel Messi",
    "shortName": "Messi",
    "teamCode": "ARG",
    "position": "FWD",
    "price": "12.00",
    "totalPoints": 62,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_arg_4",
    "name": "JuliÃ¡n Ãlvarez",
    "shortName": "Ãlvarez",
    "teamCode": "ARG",
    "position": "FWD",
    "price": "9.50",
    "totalPoints": 45,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_arg_5",
    "name": "Enzo FernÃ¡ndez",
    "shortName": "E. FernÃ¡ndez",
    "teamCode": "ARG",
    "position": "MID",
    "price": "7.50",
    "totalPoints": 32,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_fra_1",
    "name": "Mike Maignan",
    "shortName": "Maignan",
    "teamCode": "FRA",
    "position": "GK",
    "price": "5.00",
    "totalPoints": 26,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_fra_2",
    "name": "Theo HernÃ¡ndez",
    "shortName": "T. HernÃ¡ndez",
    "teamCode": "FRA",
    "position": "DEF",
    "price": "6.50",
    "totalPoints": 30,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_fra_3",
    "name": "Kylian MbappÃ©",
    "shortName": "MbappÃ©",
    "teamCode": "FRA",
    "position": "FWD",
    "price": "12.50",
    "totalPoints": 65,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_fra_4",
    "name": "Antoine Griezmann",
    "shortName": "Griezmann",
    "teamCode": "FRA",
    "position": "MID",
    "price": "9.00",
    "totalPoints": 42,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_fra_5",
    "name": "AurÃ©lien TchouamÃ©ni",
    "shortName": "TchouamÃ©ni",
    "teamCode": "FRA",
    "position": "MID",
    "price": "6.50",
    "totalPoints": 24,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_eng_1",
    "name": "Jordan Pickford",
    "shortName": "Pickford",
    "teamCode": "ENG",
    "position": "GK",
    "price": "5.00",
    "totalPoints": 22,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_eng_2",
    "name": "Trent Alexander-Arnold",
    "shortName": "TAA",
    "teamCode": "ENG",
    "position": "DEF",
    "price": "7.00",
    "totalPoints": 35,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_eng_3",
    "name": "Jude Bellingham",
    "shortName": "Bellingham",
    "teamCode": "ENG",
    "position": "MID",
    "price": "10.50",
    "totalPoints": 55,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_eng_4",
    "name": "Phil Foden",
    "shortName": "Foden",
    "teamCode": "ENG",
    "position": "MID",
    "price": "9.00",
    "totalPoints": 44,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_eng_5",
    "name": "Harry Kane",
    "shortName": "Kane",
    "teamCode": "ENG",
    "position": "FWD",
    "price": "11.00",
    "totalPoints": 52,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_esp_1",
    "name": "Unai SimÃ³n",
    "shortName": "U. SimÃ³n",
    "teamCode": "ESP",
    "position": "GK",
    "price": "5.00",
    "totalPoints": 24,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_esp_2",
    "name": "Dani Carvajal",
    "shortName": "Carvajal",
    "teamCode": "ESP",
    "position": "DEF",
    "price": "6.00",
    "totalPoints": 28,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_esp_3",
    "name": "Pedri",
    "shortName": "Pedri",
    "teamCode": "ESP",
    "position": "MID",
    "price": "8.50",
    "totalPoints": 38,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_esp_4",
    "name": "Lamine Yamal",
    "shortName": "Yamal",
    "teamCode": "ESP",
    "position": "FWD",
    "price": "10.00",
    "totalPoints": 48,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_esp_5",
    "name": "Ãlvaro Morata",
    "shortName": "Morata",
    "teamCode": "ESP",
    "position": "FWD",
    "price": "7.50",
    "totalPoints": 30,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ger_1",
    "name": "Marc-AndrÃ© ter Stegen",
    "shortName": "ter Stegen",
    "teamCode": "GER",
    "position": "GK",
    "price": "5.00",
    "totalPoints": 25,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ger_2",
    "name": "Antonio RÃ¼diger",
    "shortName": "RÃ¼diger",
    "teamCode": "GER",
    "position": "DEF",
    "price": "5.50",
    "totalPoints": 22,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ger_3",
    "name": "Jamal Musiala",
    "shortName": "Musiala",
    "teamCode": "GER",
    "position": "MID",
    "price": "9.50",
    "totalPoints": 46,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ger_4",
    "name": "Florian Wirtz",
    "shortName": "Wirtz",
    "teamCode": "GER",
    "position": "MID",
    "price": "9.00",
    "totalPoints": 43,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ger_5",
    "name": "Kai Havertz",
    "shortName": "Havertz",
    "teamCode": "GER",
    "position": "FWD",
    "price": "7.50",
    "totalPoints": 32,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_por_1",
    "name": "Diogo Costa",
    "shortName": "D. Costa",
    "teamCode": "POR",
    "position": "GK",
    "price": "4.50",
    "totalPoints": 20,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_por_2",
    "name": "RÃºben Dias",
    "shortName": "R. Dias",
    "teamCode": "POR",
    "position": "DEF",
    "price": "6.00",
    "totalPoints": 26,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_por_3",
    "name": "Bruno Fernandes",
    "shortName": "B. Fernandes",
    "teamCode": "POR",
    "position": "MID",
    "price": "9.50",
    "totalPoints": 48,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_por_4",
    "name": "Cristiano Ronaldo",
    "shortName": "Ronaldo",
    "teamCode": "POR",
    "position": "FWD",
    "price": "10.00",
    "totalPoints": 40,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_por_5",
    "name": "Rafael LeÃ£o",
    "shortName": "LeÃ£o",
    "teamCode": "POR",
    "position": "FWD",
    "price": "8.50",
    "totalPoints": 36,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ned_1",
    "name": "Bart Verbruggen",
    "shortName": "Verbruggen",
    "teamCode": "NED",
    "position": "GK",
    "price": "4.50",
    "totalPoints": 18,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ned_2",
    "name": "Virgil van Dijk",
    "shortName": "Van Dijk",
    "teamCode": "NED",
    "position": "DEF",
    "price": "6.50",
    "totalPoints": 30,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ned_3",
    "name": "Frenkie de Jong",
    "shortName": "De Jong",
    "teamCode": "NED",
    "position": "MID",
    "price": "7.50",
    "totalPoints": 28,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ned_4",
    "name": "Cody Gakpo",
    "shortName": "Gakpo",
    "teamCode": "NED",
    "position": "FWD",
    "price": "8.00",
    "totalPoints": 38,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ned_5",
    "name": "Memphis Depay",
    "shortName": "Depay",
    "teamCode": "NED",
    "position": "FWD",
    "price": "7.50",
    "totalPoints": 30,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_col_1",
    "name": "David Ospina",
    "shortName": "Ospina",
    "teamCode": "COL",
    "position": "GK",
    "price": "4.50",
    "totalPoints": 16,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_col_2",
    "name": "Davinson SÃ¡nchez",
    "shortName": "SÃ¡nchez",
    "teamCode": "COL",
    "position": "DEF",
    "price": "5.00",
    "totalPoints": 18,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_col_3",
    "name": "James RodrÃ­guez",
    "shortName": "James",
    "teamCode": "COL",
    "position": "MID",
    "price": "7.00",
    "totalPoints": 30,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_col_4",
    "name": "Luis DÃ­az",
    "shortName": "L. DÃ­az",
    "teamCode": "COL",
    "position": "FWD",
    "price": "8.50",
    "totalPoints": 40,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_col_5",
    "name": "Rafael Santos BorrÃ©",
    "shortName": "BorrÃ©",
    "teamCode": "COL",
    "position": "FWD",
    "price": "6.50",
    "totalPoints": 24,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_jpn_1",
    "name": "Shuichi Gonda",
    "shortName": "Gonda",
    "teamCode": "JPN",
    "position": "GK",
    "price": "4.00",
    "totalPoints": 14,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_jpn_2",
    "name": "Takehiro Tomiyasu",
    "shortName": "Tomiyasu",
    "teamCode": "JPN",
    "position": "DEF",
    "price": "5.00",
    "totalPoints": 20,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_jpn_3",
    "name": "Takefusa Kubo",
    "shortName": "Kubo",
    "teamCode": "JPN",
    "position": "MID",
    "price": "7.50",
    "totalPoints": 34,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_jpn_4",
    "name": "Kaoru Mitoma",
    "shortName": "Mitoma",
    "teamCode": "JPN",
    "position": "MID",
    "price": "7.00",
    "totalPoints": 30,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_jpn_5",
    "name": "Kyogo Furuhashi",
    "shortName": "Furuhashi",
    "teamCode": "JPN",
    "position": "FWD",
    "price": "6.50",
    "totalPoints": 26,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_mex_1",
    "name": "Guillermo Ochoa",
    "shortName": "Ochoa",
    "teamCode": "MEX",
    "position": "GK",
    "price": "4.50",
    "totalPoints": 18,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_mex_2",
    "name": "Jorge SÃ¡nchez",
    "shortName": "J. SÃ¡nchez",
    "teamCode": "MEX",
    "position": "DEF",
    "price": "4.50",
    "totalPoints": 15,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_mex_3",
    "name": "Hirving Lozano",
    "shortName": "Lozano",
    "teamCode": "MEX",
    "position": "MID",
    "price": "7.00",
    "totalPoints": 28,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_mex_4",
    "name": "Santiago GimÃ©nez",
    "shortName": "S. GimÃ©nez",
    "teamCode": "MEX",
    "position": "FWD",
    "price": "7.50",
    "totalPoints": 32,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_mar_1",
    "name": "Yassine Bounou",
    "shortName": "Bounou",
    "teamCode": "MAR",
    "position": "GK",
    "price": "5.00",
    "totalPoints": 24,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_mar_2",
    "name": "Achraf Hakimi",
    "shortName": "Hakimi",
    "teamCode": "MAR",
    "position": "DEF",
    "price": "6.50",
    "totalPoints": 30,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_mar_3",
    "name": "Hakim Ziyech",
    "shortName": "Ziyech",
    "teamCode": "MAR",
    "position": "MID",
    "price": "7.00",
    "totalPoints": 28,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_mar_4",
    "name": "Youssef En-Nesyri",
    "shortName": "En-Nesyri",
    "teamCode": "MAR",
    "position": "FWD",
    "price": "6.50",
    "totalPoints": 26,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_sen_1",
    "name": "Ã‰douard Mendy",
    "shortName": "Mendy",
    "teamCode": "SEN",
    "position": "GK",
    "price": "4.50",
    "totalPoints": 18,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_sen_2",
    "name": "Kalidou Koulibaly",
    "shortName": "Koulibaly",
    "teamCode": "SEN",
    "position": "DEF",
    "price": "5.50",
    "totalPoints": 22,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_sen_3",
    "name": "Sadio ManÃ©",
    "shortName": "ManÃ©",
    "teamCode": "SEN",
    "position": "MID",
    "price": "8.00",
    "totalPoints": 36,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_sen_4",
    "name": "IsmaÃ¯la Sarr",
    "shortName": "Sarr",
    "teamCode": "SEN",
    "position": "FWD",
    "price": "6.50",
    "totalPoints": 26,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_cro_1",
    "name": "Dominik LivakoviÄ‡",
    "shortName": "LivakoviÄ‡",
    "teamCode": "CRO",
    "position": "GK",
    "price": "4.50",
    "totalPoints": 20,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_cro_2",
    "name": "JoÅ¡ko Gvardiol",
    "shortName": "Gvardiol",
    "teamCode": "CRO",
    "position": "DEF",
    "price": "6.00",
    "totalPoints": 26,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_cro_3",
    "name": "Luka ModriÄ‡",
    "shortName": "ModriÄ‡",
    "teamCode": "CRO",
    "position": "MID",
    "price": "7.50",
    "totalPoints": 32,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_cro_4",
    "name": "Andrej KramariÄ‡",
    "shortName": "KramariÄ‡",
    "teamCode": "CRO",
    "position": "FWD",
    "price": "7.00",
    "totalPoints": 28,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_bel_1",
    "name": "Thibaut Courtois",
    "shortName": "Courtois",
    "teamCode": "BEL",
    "position": "GK",
    "price": "5.50",
    "totalPoints": 26,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_bel_2",
    "name": "Timothy Castagne",
    "shortName": "Castagne",
    "teamCode": "BEL",
    "position": "DEF",
    "price": "5.00",
    "totalPoints": 18,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_bel_3",
    "name": "Kevin De Bruyne",
    "shortName": "De Bruyne",
    "teamCode": "BEL",
    "position": "MID",
    "price": "10.00",
    "totalPoints": 50,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_bel_4",
    "name": "Romelu Lukaku",
    "shortName": "Lukaku",
    "teamCode": "BEL",
    "position": "FWD",
    "price": "8.50",
    "totalPoints": 36,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_uru_1",
    "name": "Sergio Rochet",
    "shortName": "Rochet",
    "teamCode": "URU",
    "position": "GK",
    "price": "4.50",
    "totalPoints": 16,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_uru_2",
    "name": "Ronald AraÃºjo",
    "shortName": "AraÃºjo",
    "teamCode": "URU",
    "position": "DEF",
    "price": "5.50",
    "totalPoints": 22,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_uru_3",
    "name": "Federico Valverde",
    "shortName": "Valverde",
    "teamCode": "URU",
    "position": "MID",
    "price": "8.00",
    "totalPoints": 38,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_uru_4",
    "name": "Darwin NÃºÃ±ez",
    "shortName": "NÃºÃ±ez",
    "teamCode": "URU",
    "position": "FWD",
    "price": "8.50",
    "totalPoints": 36,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ita_1",
    "name": "Gianluigi Donnarumma",
    "shortName": "Donnarumma",
    "teamCode": "ITA",
    "position": "GK",
    "price": "5.00",
    "totalPoints": 22,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ita_2",
    "name": "Alessandro Bastoni",
    "shortName": "Bastoni",
    "teamCode": "ITA",
    "position": "DEF",
    "price": "5.50",
    "totalPoints": 24,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ita_3",
    "name": "NicolÃ² Barella",
    "shortName": "Barella",
    "teamCode": "ITA",
    "position": "MID",
    "price": "7.50",
    "totalPoints": 34,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_ita_4",
    "name": "Gianluca Scamacca",
    "shortName": "Scamacca",
    "teamCode": "ITA",
    "position": "FWD",
    "price": "7.00",
    "totalPoints": 28,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_kor_1",
    "name": "Kim Seung-gyu",
    "shortName": "Kim S.",
    "teamCode": "KOR",
    "position": "GK",
    "price": "4.00",
    "totalPoints": 14,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_kor_2",
    "name": "Kim Min-jae",
    "shortName": "Kim M.",
    "teamCode": "KOR",
    "position": "DEF",
    "price": "5.50",
    "totalPoints": 24,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_kor_3",
    "name": "Son Heung-min",
    "shortName": "Son",
    "teamCode": "KOR",
    "position": "FWD",
    "price": "10.00",
    "totalPoints": 48,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_kor_4",
    "name": "Lee Kang-in",
    "shortName": "Lee K.",
    "teamCode": "KOR",
    "position": "MID",
    "price": "7.00",
    "totalPoints": 30,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_can_1",
    "name": "Milan Borjan",
    "shortName": "Borjan",
    "teamCode": "CAN",
    "position": "GK",
    "price": "4.00",
    "totalPoints": 14,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_can_2",
    "name": "Alphonso Davies",
    "shortName": "Davies",
    "teamCode": "CAN",
    "position": "DEF",
    "price": "6.50",
    "totalPoints": 28,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_can_3",
    "name": "Jonathan David",
    "shortName": "J. David",
    "teamCode": "CAN",
    "position": "FWD",
    "price": "8.00",
    "totalPoints": 36,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_can_4",
    "name": "Stephen EustÃ¡quio",
    "shortName": "EustÃ¡quio",
    "teamCode": "CAN",
    "position": "MID",
    "price": "5.50",
    "totalPoints": 20,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_egy_1",
    "name": "Mohamed El-Shenawy",
    "shortName": "El-Shenawy",
    "teamCode": "EGY",
    "position": "GK",
    "price": "4.50",
    "totalPoints": 16,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_egy_2",
    "name": "Ahmed Hegazi",
    "shortName": "Hegazi",
    "teamCode": "EGY",
    "position": "DEF",
    "price": "4.50",
    "totalPoints": 14,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_egy_3",
    "name": "Mohamed Salah",
    "shortName": "Salah",
    "teamCode": "EGY",
    "position": "FWD",
    "price": "11.00",
    "totalPoints": 54,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_egy_4",
    "name": "Omar Marmoush",
    "shortName": "Marmoush",
    "teamCode": "EGY",
    "position": "FWD",
    "price": "8.00",
    "totalPoints": 34,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_nga_1",
    "name": "Francis Uzoho",
    "shortName": "Uzoho",
    "teamCode": "NGA",
    "position": "GK",
    "price": "4.00",
    "totalPoints": 12,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_nga_2",
    "name": "William Troost-Ekong",
    "shortName": "Ekong",
    "teamCode": "NGA",
    "position": "DEF",
    "price": "4.50",
    "totalPoints": 16,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_nga_3",
    "name": "Victor Osimhen",
    "shortName": "Osimhen",
    "teamCode": "NGA",
    "position": "FWD",
    "price": "9.50",
    "totalPoints": 44,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_nga_4",
    "name": "Alex Iwobi",
    "shortName": "Iwobi",
    "teamCode": "NGA",
    "position": "MID",
    "price": "6.00",
    "totalPoints": 22,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_sui_1",
    "name": "Yann Sommer",
    "shortName": "Sommer",
    "teamCode": "SUI",
    "position": "GK",
    "price": "4.50",
    "totalPoints": 18,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_sui_2",
    "name": "Manuel Akanji",
    "shortName": "Akanji",
    "teamCode": "SUI",
    "position": "DEF",
    "price": "5.50",
    "totalPoints": 22,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_sui_3",
    "name": "Granit Xhaka",
    "shortName": "Xhaka",
    "teamCode": "SUI",
    "position": "MID",
    "price": "6.50",
    "totalPoints": 26,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_sui_4",
    "name": "Breel Embolo",
    "shortName": "Embolo",
    "teamCode": "SUI",
    "position": "FWD",
    "price": "6.00",
    "totalPoints": 22,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_sau_1",
    "name": "Mohammed Al-Owais",
    "shortName": "Al-Owais",
    "teamCode": "KSA",
    "position": "GK",
    "price": "4.00",
    "totalPoints": 14,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_sau_2",
    "name": "Hassan Tambakti",
    "shortName": "Tambakti",
    "teamCode": "KSA",
    "position": "DEF",
    "price": "4.00",
    "totalPoints": 12,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_sau_3",
    "name": "Salem Al-Dawsari",
    "shortName": "Al-Dawsari",
    "teamCode": "KSA",
    "position": "MID",
    "price": "6.50",
    "totalPoints": 26,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  },
  {
    "frontendId": "p_sau_4",
    "name": "Firas Al-Buraikan",
    "shortName": "Al-Buraikan",
    "teamCode": "KSA",
    "position": "FWD",
    "price": "5.50",
    "totalPoints": 18,
    "minutesPlayed": 0,
    "isInjured": false,
    "isSuspended": false,
    "isActive": true
  }
] as const;

